# Generated by Django 4.2.4 on 2023-08-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='necsubject',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
