# Generated by Django 4.2.4 on 2023-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelset',
            options={'ordering': ['set_name']},
        ),
        migrations.AlterModelOptions(
            name='necsubject',
            options={'ordering': ['subject_name']},
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'None')], max_length=1, null=True),
        ),
    ]
