# Generated by Django 4.2.4 on 2023-09-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nec', '0002_remove_modelset_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelset',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nec.necsubject'),
        ),
    ]
