# Generated by Django 4.2.4 on 2023-10-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nec', '0002_alter_modelset_options_alter_necsubject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='necsubject',
            name='picture_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
