# Generated by Django 4.2.4 on 2023-10-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nec', '0003_necsubject_picture_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_code', models.CharField(max_length=20, unique=True)),
                ('parent_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nec.chapter')),
            ],
            options={
                'ordering': ['chapter_code'],
            },
        ),
        migrations.AddField(
            model_name='necsubject',
            name='subject_code',
            field=models.CharField(default='EMPTY', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic_name', models.CharField(max_length=255)),
                ('chapter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nec.chapter', verbose_name='Sub-chapter')),
            ],
            options={
                'ordering': ['chapter__chapter_code', 'created_at'],
            },
        ),
    ]
