# Generated by Django 4.2.4 on 2023-08-12 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nec', '0003_alter_necsubject_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necsubject',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
