# Generated by Django 4.2.4 on 2023-09-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nec', '0003_modelset_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='necsubject',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='necsubject',
            name='subject_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
