# Generated by Django 4.2.4 on 2023-08-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nec', '0004_alter_necsubject_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.CharField(blank=True, choices=[('a', 'A Group'), ('b', 'B Group')], max_length=1, null=True),
        ),
    ]
